### ISSUE TITLE
to_a should return a multidimensional array

### ISSUE THREAD

**Issue by watzon** [Exilor/matrix#5]
I feel like it would make sense since this is a matrix, that `to_a` would return a multidimensional array. Or maybe there could be a `to_multi` method or something?

**Comment by JacobUb** [comment]
You mean [this](https://github.com/Exilor/matrix/blob/master/src/matrix.cr#L402)?

**Comment by watzon** [comment]
I was thinking a multidimensional array for the whole matrix, not just the rows and columns separately

**Comment by JacobUb** [comment]
If the rows and columns aren't separated I don't see how the array could be multidimensional 😕 
```crystal
m = Matrix.new(3, 4, &.itself)
puts m
# ┌ 0  1  2  3┐
# │ 4  5  6  7│
# └ 8  9 10 11┘
p m.rows # [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
```
Isn't this how a matrix is represented as an array of arrays?

**Comment by watzon** [comment]
You know what? I wasn't thinking it through fully. Rows works fine
